# name: Dummy-golangci-lint
# on:
#   push:
#     branches:
#       - master
#       - main
#   pull_request:
#     branches:
#       - main
# 
# jobs:
#   golangci:
#     name: lint
#     runs-on: ubuntu-latest
#     steps:
#       - name: Exit with success
#         run: exit 0

 name: dynamic-execution
 on:
   push:
     branches:
       - master
       - main
   pull_request:
     branches:
       - main
 jobs:
    dynamic:
     name: dynamic
     runs-on: ubuntu-latest
     steps:
       - name: Create dummy workflow
         env:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           personal_github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
         run: |
           echo ${GITHUB_SHA::8}
           echo ${GITHUB_SHA}

             # -H "Accept: application/vnd.github.v3+json" \
           curl \
             -X PATCH \
             --header "Accept: application/vnd.github.v3+json" \
             --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             https://api.github.com/repos/${{ github.repository }}/branches/docs/protection/required_status_checks \
             -d '{"strict":true}'


             # -d '{"strict":false}'
           # curl \
           #   -X POST \
           #   -H "Accept: application/vnd.github.v3+json" \
           #   https://api.github.com/repos/funapy-sandbox/actions-sandbox/statuses/${GITHUB_SHA::8} \
           #   -d '{"state":"success"}'
           # curl \
           #   -X PUT \
           #   -H "Accept: application/vnd.github.v3+json" \
           #   https://api.github.com/repos/funapy-sandbox/actions-sandbox/actions/workflows/golangci-lint.yml/enable
           # curl \
           #   -X PUT \
           #   -H "Accept: application/vnd.github.v3+json" \
           #   -H "Authorization: ${PERSONAL_GITHUB_TOKEN}" \
           #   https://api.github.com/repos/funapy-sandbox/actions-sandbox/actions/workflows/golangci-lint.yml/enable
           # yaml="
           # name: Dummy-golangci-lint
           # on:
           #   push:
           #     branches:
           #       - master
           #       - main
           #   pull_request:
           #     branches:
           #       - main
           # jobs:
           #   golangci:
           #     name: lint
           #     runs-on: ubuntu-latest
           #     steps:
           #       - name: Exit with success
           #         run: exit 0
           # "
           # echo "$yaml"
           # 
           # encoded=`echo $str | base64`
           # echo $encoded
           # 
           # curl \
           #   -H "Accept: application/vnd.github.v3+json" \
           #   https://api.github.com/repos/funapy-sandbox/actions-sandbox/actions/workflows
           # 
           # curl --request POST \
           #      --url "https://api.github.com/repos/funapy-sandbox/actions-sandbox/contents/.github/workflows/test.yml" \
           #      --header "authorization: Bearer ${GITHUB_TOKEN}" \
           #      --header 'content-type: application/json' \
           #      --data "$encoded"
           exit 0
