name: Force Status Update
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - main
jobs:
  dynamic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git rev-parse --short HEAD
      - run: echo ${{ github.sha }}
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - name: Execute update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHA: ${{ github.event.pull_request.head.sha }}
        run: go run main.go
