name: Force Status Update
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - main
jobs:
  dynamic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git rev-parse --short HEAD
      - name: For Test
        run: |
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/funapy-sandbox/actions-sandbox/branches/main/protection
      - run: echo ${{ github.sha }}
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - name: Execute update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHA: ${{ github.event.pull_request.head.sha }}
        run: go run main.go
