name: dynamic-execution
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - main
jobs:
   dynamic:
    name: dynamic
    runs-on: ubuntu-latest
    steps:
      - name: Force Success Status
        if: ${{ always() }}
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_SHA::8}
          echo ${GITHUB_SHA}

          # -H "Accept: application/vnd.github.v3+json" \
          # curl \
          #   -X POST \
          #   -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          #   -H "Content-Type: application/json" \
          #   -d "{\"name\":\"lint\", \"head_sha\": \"${GITHUB_SHA}\", \"status\": \"completed\", \"conclusion\": \"success\"}" \
          #   https://api.github.com/repos/funapy-sandbox/actions-sandbox/check-runs
          #
          # curl \
          #   -X PATCH \
          #   -H "Authorization: token ${{ secrets.PERSONAL_GITHUB_TOKEN }}" \
          #   -H "Accept: application/vnd.github.v3+json" \
          #   https://api.github.com/repos/funapy-sandbox/actions-sandbox/branches/docs/protection/required_status_checks \
          #   -d '{"strict":false, "contexts": "lint"}'
          #
          # echo "update status"
          # curl \
          #   -X POST \
          #   -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          #   -H "Content-Type: application/json" \
          #   -d "{\"state\": \"success\", \"target_url\": \"http://localhost:8080\", \"description\": \"test\", \"context\": \"lint\"}" \
          #   https://api.github.com/repos/${{ github.repository }}/statuses/${GITHUB_SHA}
          #
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "lint",
            "state": "success",
            "description": "lint passed"
          }'
