name: dynamic-execution
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - main
jobs:
  dynamic:
    name: dynamic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - name: Execute update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHA: ${{ github.sha }}
        run: go run main.go
      - name: Sleep
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHA: ${{ github.sha }}
        run: sleep 15s
