name: dynamic-execution
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - main
jobs:
   dynamic:
    name: dynamic
    runs-on: ubuntu-latest
    steps:
      - name: Create dummy workflow
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_SHA::8}
          echo ${GITHUB_SHA}

          # -H "Accept: application/vnd.github.v3+json" \
          # curl \
          #   -X POST \
          #   -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          #   -H "Content-Type: application/json" \
          #   -d "{\"name\":\"lint\", \"head_sha\": \"${GITHUB_SHA}\", \"status\": \"completed\", \"conclusion\": \"success\"}" \
          #   https://api.github.com/repos/funapy-sandbox/actions-sandbox/check-runs

          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"state\": \"completed\", \"target_url\": \"http://localhost:8080\", \"description\": \"test\", \"context\": \"lint\"}" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${GITHUB_SHA}
